apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: apigateway:{{ .Commit }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Port }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Port }}
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: apigateway
  type: NodePort
  ports:
  - protocol: TCP
    port: 2018
    targetPort: {{ .Port }}